version: "3.7"
networks:
  demo-net:


services:
  pyspark:
    build: .
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
    networks:
      - demo-net
    volumes:
      - ./work:/home/jovyan/work
    depends_on:
      - minio
    # Carregar variáveis de ambiente do .env
    env_file:
      - .env

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: bakery
    ports:
      - "5432:5432/tcp"
    networks:
      - demo-net
    volumes:
      - ./postgres:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080/tcp"
    networks:
      - demo-net
    deploy:
      restart_policy:
        condition: on-failure

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
    ports:
      - "9000:9000"
    command: server /data
    networks:
      - demo-net
    volumes:
      - minio_data:/data

volumes:
  minio_data:
